import { Treatment, TreatmentPlan, FaceScores } from '@/types';

const ALL_TREATMENTS: Omit<Treatment, 'roi'>[] = [
  // ─── SKINCARE ───────────────────────────────────────────────────────────────
  {
    id: 'sunscreen',
    name: '高倍防曬 SPF50+',
    nameEn: 'Broad-Spectrum Sunscreen',
    category: 'skincare',
    emoji: '☀️',
    targetDimensions: ['skinTexture', 'youthfulness'],
    improvementPoints: 8,
    costMin: 300,
    costMax: 900,
    costUnit: 'month',
    timeToResultsWeeks: 1,
    maintenanceMonths: 1,
    effort: 'low',
    description: '防曬是所有保養的地基。紫外線是造成色斑、細紋、膚色暗沉的首要原因，每日使用 SPF50+ 可立即防止進一步損傷，並讓其他保養品效果加倍。',
    tips: ['早上洗臉後最後一步使用', '室內也需補充（藍光+UVA可穿透玻璃）', '每2小時補擦一次', '選含氧化鋅的物理性防曬更溫和'],
  },
  {
    id: 'aha-bha',
    name: '果酸/水楊酸去角質',
    nameEn: 'AHA/BHA Exfoliant',
    category: 'skincare',
    emoji: '🧪',
    targetDimensions: ['skinTexture', 'youthfulness'],
    improvementPoints: 10,
    costMin: 350,
    costMax: 1200,
    costUnit: 'month',
    timeToResultsWeeks: 2,
    maintenanceMonths: 1,
    effort: 'low',
    description: '果酸（AHA）去除表層死皮細胞讓膚色更亮，水楊酸（BHA）深入毛孔溶解皮脂。2–4週可明顯感受毛孔細緻、膚質提升，是最快改善肌理分的保養品。',
    tips: ['初始每週2次，適應後再增加頻率', '使用後一定要防曬', '乾敏肌從低濃度（5–8%AHA）開始', '水楊酸適合油肌/痘肌/毛孔問題'],
  },
  {
    id: 'vitamin-c',
    name: '維他命C美白精華',
    nameEn: 'Vitamin C Serum',
    category: 'skincare',
    emoji: '🍊',
    targetDimensions: ['skinTexture', 'youthfulness'],
    improvementPoints: 9,
    costMin: 500,
    costMax: 2500,
    costUnit: 'month',
    timeToResultsWeeks: 4,
    maintenanceMonths: 1,
    effort: 'low',
    description: '維他命C是抗氧化之王，能抑制黑色素生成、提亮膚色、促進膠原蛋白合成。4–8週後可見膚色均勻、暗沉改善。搭配防曬效果加倍。',
    tips: ['早上使用效果最佳（抗氧化保護白天皮膚）', '選20% L-抗壞血酸或15% 維他命C衍生物', '冷藏保存避免氧化', '搭配維他命E和阿魏酸效果更好'],
  },
  {
    id: 'hyaluronic-acid',
    name: '玻尿酸保濕精華',
    nameEn: 'Hyaluronic Acid Serum',
    category: 'skincare',
    emoji: '💧',
    targetDimensions: ['youthfulness', 'skinTexture'],
    improvementPoints: 6,
    costMin: 400,
    costMax: 1500,
    costUnit: 'month',
    timeToResultsWeeks: 1,
    maintenanceMonths: 1,
    effort: 'low',
    description: '玻尿酸可鎖住大量水分，立即讓皮膚看起來更飽滿水潤。缺水的細紋和暗沉在補水後即可改善。效果快但需持續使用維持。',
    tips: ['在略微潮濕的皮膚上使用吸收更好', '選多分子量玻尿酸同時作用於不同層次', '用後立即鎖上保濕霜避免水分蒸發', '乾燥環境需加強頻率'],
  },
  {
    id: 'niacinamide',
    name: '菸鹼醯胺（維他命B3）精華',
    nameEn: 'Niacinamide Serum',
    category: 'skincare',
    emoji: '🔬',
    targetDimensions: ['skinTexture', 'youthfulness'],
    improvementPoints: 8,
    costMin: 300,
    costMax: 1200,
    costUnit: 'month',
    timeToResultsWeeks: 4,
    maintenanceMonths: 1,
    effort: 'low',
    description: '菸鹼醯胺（5–10%）能縮小毛孔外觀、淡化色斑、調節皮脂分泌、強化皮膚屏障。適合所有膚質，溫和且可與多數成分混用。',
    tips: ['濃度10%以下較不刺激', '早晚皆可使用', '可與玻尿酸、視黃醇混搭', '對泛紅和敏感肌有鎮靜效果'],
  },
  {
    id: 'retinol',
    name: 'A醇（視黃醇）精華',
    nameEn: 'Retinol Serum',
    category: 'skincare',
    emoji: '⚗️',
    targetDimensions: ['skinTexture', 'youthfulness', 'contour'],
    improvementPoints: 14,
    costMin: 600,
    costMax: 3000,
    costUnit: 'month',
    timeToResultsWeeks: 12,
    maintenanceMonths: 1,
    effort: 'medium',
    description: '視黃醇是有最多臨床研究支持的抗老成分，能加速細胞更新、刺激膠原蛋白生成、改善細紋和膚質。12–16週後效果最顯著，是長期肌膚改造的核心。',
    tips: ['從低濃度（0.025–0.1%）開始，每週2–3次', '只在晚上使用', '初期可能有脫皮刺激（爛臉期），屬正常', '使用期間加強防曬和保濕'],
  },
  {
    id: 'peptide',
    name: '胜肽緊緻精華',
    nameEn: 'Peptide Firming Serum',
    category: 'skincare',
    emoji: '💪',
    targetDimensions: ['youthfulness', 'contour', 'skinTexture'],
    improvementPoints: 8,
    costMin: 800,
    costMax: 3000,
    costUnit: 'month',
    timeToResultsWeeks: 8,
    maintenanceMonths: 1,
    effort: 'low',
    description: '胜肽是皮膚訊號蛋白，能刺激膠原蛋白和彈力蛋白合成。多胜肽配方可改善皮膚緊緻度、減少法令紋、提升整體輪廓感。',
    tips: ['搭配維他命C效果更好', '早晚皆可使用', '輕柔按摩幫助吸收', '選含Argireline、Matrixyl等多種胜肽的配方'],
  },
  {
    id: 'eye-cream',
    name: '眼部精華/眼霜',
    nameEn: 'Eye Serum & Cream',
    category: 'skincare',
    emoji: '👁️',
    targetDimensions: ['youthfulness', 'skinTexture'],
    improvementPoints: 7,
    costMin: 500,
    costMax: 3500,
    costUnit: 'month',
    timeToResultsWeeks: 4,
    maintenanceMonths: 1,
    effort: 'low',
    description: '眼周肌膚最薄最脆弱，針對性保養可改善黑眼圈、細紋、浮腫。含咖啡因可消腫，視黃醇可去細紋，維他命K可淡化黑眼圈。',
    tips: ['用無名指輕點塗抹，避免拉扯', '早上用咖啡因消腫，晚上用視黃醇修護', '冰敷眼膜可緊急消腫', '保持充足睡眠比任何眼霜都有效'],
  },
  {
    id: 'ceramide-moisturizer',
    name: '神經醯胺屏障修護霜',
    nameEn: 'Ceramide Barrier Moisturizer',
    category: 'skincare',
    emoji: '🛡️',
    targetDimensions: ['skinTexture', 'youthfulness'],
    improvementPoints: 6,
    costMin: 400,
    costMax: 1800,
    costUnit: 'month',
    timeToResultsWeeks: 2,
    maintenanceMonths: 1,
    effort: 'low',
    description: '神經醯胺是皮膚屏障的關鍵成分。屏障受損會導致水分流失、泛紅、敏感。補充神經醯胺可修護屏障，讓其他保養品吸收更好。',
    tips: ['適合所有膚質，特別是敏感乾性肌', '在精華後使用鎖住水分', '可全年使用，冬天加厚或加倍', '含神經醯胺1、3、6-II最完整'],
  },

  // ─── PROFESSIONAL TREATMENTS ────────────────────────────────────────────────
  {
    id: 'hydrafacial',
    name: '水飛梭煥膚',
    nameEn: 'HydraFacial',
    category: 'professional',
    emoji: '🌊',
    targetDimensions: ['skinTexture', 'youthfulness'],
    improvementPoints: 10,
    costMin: 3500,
    costMax: 8000,
    costUnit: 'treatment',
    timeToResultsWeeks: 0,
    maintenanceMonths: 1,
    effort: 'low',
    description: '結合深層清潔、去角質、螺旋吸出毛孔髒污和注入精華三步驟。術後即刻看到毛孔細緻、膚色提亮效果，無恢復期。每月一次保持效果最佳。',
    tips: ['適合婚前、活動前急速補妝感', '術後補充防曬', '可搭配導入客製精華', '推薦每月一次做基礎維護'],
  },
  {
    id: 'ipl',
    name: 'IPL光子嫩膚',
    nameEn: 'Intense Pulsed Light',
    category: 'professional',
    emoji: '✨',
    targetDimensions: ['skinTexture', 'youthfulness'],
    improvementPoints: 12,
    costMin: 3000,
    costMax: 10000,
    costUnit: 'treatment',
    timeToResultsWeeks: 2,
    maintenanceMonths: 9,
    effort: 'low',
    description: 'IPL可同時改善色斑、泛紅、血管擴張，刺激膠原蛋白生成。建議3–5次療程，每次間隔3–4週，維持9–12個月。',
    tips: ['術前術後加強防曬', '色斑治療後會先變深再脫落', '適合膚色較淺者效果最好', '可搭配果酸換膚提升整體效果'],
  },
  {
    id: 'botox',
    name: '肉毒桿菌注射',
    nameEn: 'Botulinum Toxin (Botox)',
    category: 'professional',
    emoji: '💉',
    targetDimensions: ['symmetry', 'youthfulness', 'proportion'],
    improvementPoints: 15,
    costMin: 5000,
    costMax: 20000,
    costUnit: 'treatment',
    timeToResultsWeeks: 2,
    maintenanceMonths: 5,
    effort: 'low',
    description: '肉毒可放鬆過度活躍肌肉，改善動態皺紋（抬頭紋、魚尾紋、眉間紋）、提眉、瘦臉（咬肌）、改善不對稱。效果自然，2週完全發揮，維持4–6月。',
    tips: ['注射後4小時避免躺下、劇烈運動', '選擇有執照的醫師注射', '定期回診可預防過度補打', '瘦臉針需3–4次才達最佳效果'],
  },
  {
    id: 'filler',
    name: '玻尿酸填充注射',
    nameEn: 'Hyaluronic Acid Filler',
    category: 'professional',
    emoji: '💊',
    targetDimensions: ['contour', 'proportion', 'youthfulness'],
    improvementPoints: 18,
    costMin: 8000,
    costMax: 40000,
    costUnit: 'treatment',
    timeToResultsWeeks: 0,
    maintenanceMonths: 15,
    effort: 'low',
    description: '玻尿酸填充可立即改善臉型輪廓、補充流失的臉部脂肪、修飾五官比例（墊鼻、豐唇、拉提蘋果肌）。效果立現，維持12–18月。',
    tips: ['術後24小時避免按壓', '選用HA交聯程度適合部位的填充劑', '初次建議少量保守', '可用酵素溶解，安全性高'],
  },
  {
    id: 'fractional-laser',
    name: '飛梭雷射/點陣雷射',
    nameEn: 'Fractional Laser',
    category: 'professional',
    emoji: '🔆',
    targetDimensions: ['skinTexture', 'youthfulness', 'proportion'],
    improvementPoints: 18,
    costMin: 8000,
    costMax: 30000,
    costUnit: 'treatment',
    timeToResultsWeeks: 3,
    maintenanceMonths: 18,
    effort: 'medium',
    description: '飛梭雷射用微小光柱刺激皮膚再生，大幅改善毛孔、細紋、疤痕、膚色不均。非侵入式，恢復期3–5天（泛紅脫皮），一療程3次，效果可維持1.5–2年。',
    tips: ['術後嚴格防曬至少一個月', '術後2週內避免高溫環境', '可搭配導入生長因子加速修復', '治療前停用A醇和果酸1–2週'],
  },
  {
    id: 'prp',
    name: 'PRP自體血清治療',
    nameEn: 'PRP (Platelet-Rich Plasma)',
    category: 'professional',
    emoji: '🩸',
    targetDimensions: ['skinTexture', 'youthfulness'],
    improvementPoints: 10,
    costMin: 8000,
    costMax: 20000,
    costUnit: 'treatment',
    timeToResultsWeeks: 4,
    maintenanceMonths: 12,
    effort: 'low',
    description: '抽取自身血液分離出高濃度血小板，注射回皮膚刺激天然修復。可改善膚質、淡化黑眼圈、緊緻鬆弛，適合天然派或對異物有顧慮者。',
    tips: ['需連續3次治療（每月一次）才有最佳效果', '可搭配微針導入效果更好', '術後補充鐵質和蛋白質輔助', '結果因個人差異大，部分人反應佳'],
  },
  {
    id: 'ultherapy',
    name: '音波拉皮（海芙/烏托邦）',
    nameEn: 'High-Intensity Focused Ultrasound',
    category: 'professional',
    emoji: '🔊',
    targetDimensions: ['contour', 'youthfulness'],
    improvementPoints: 12,
    costMin: 20000,
    costMax: 70000,
    costUnit: 'treatment',
    timeToResultsWeeks: 8,
    maintenanceMonths: 18,
    effort: 'low',
    description: '高能聚焦超音波深達筋膜層（SMAS），刺激深層膠原蛋白生成，達到拉提緊緻效果。2–4月後效果最佳，維持12–24月。',
    tips: ['術後可能有輕度腫脹，1–3天消退', '效果在3–6月內持續顯現', '一年做一次維持效果', '配合日常保養效果更長久'],
  },
  {
    id: 'thread-lift',
    name: '埋線拉皮',
    nameEn: 'Thread Lift',
    category: 'professional',
    emoji: '🧵',
    targetDimensions: ['contour', 'youthfulness', 'proportion'],
    improvementPoints: 14,
    costMin: 30000,
    costMax: 90000,
    costUnit: 'treatment',
    timeToResultsWeeks: 4,
    maintenanceMonths: 18,
    effort: 'low',
    description: '在皮膚下置入可吸收線材物理性上拉鬆弛組織，同時刺激膠原蛋白增生。改善法令紋、頰部下垂、頸紋，效果維持18–24月。',
    tips: ['術後2週內避免大笑、咀嚼硬物', '腫脹瘀青約1–2週消退', '搭配玻尿酸效果更全面', '適合30–50歲輕中度鬆弛'],
  },
];

function calcROI(t: Omit<Treatment, 'roi'>): number {
  const avgCost = (t.costMin + t.costMax) / 2;
  const timeToResultFactor = Math.max(0.5, t.timeToResultsWeeks / 4);
  const durabilityMonths = t.maintenanceMonths;

  if (t.category === 'skincare') {
    // Monthly cost, perpetual
    return (t.improvementPoints * 10) / (avgCost / 500 * timeToResultFactor);
  } else {
    // One-time cost amortized over duration
    const monthlyCost = avgCost / durabilityMonths;
    return (t.improvementPoints * 10) / (monthlyCost / 500 * timeToResultFactor);
  }
}

export function buildTreatments(scores: FaceScores): Treatment[] {
  const improvements = scores;

  return ALL_TREATMENTS
    .map(t => {
      const roi = calcROI(t);
      // Boost ROI for treatments targeting weakest dimensions
      const relevanceBoost = t.targetDimensions.reduce((sum, dim) => {
        const score = improvements[dim] ?? 70;
        return sum + Math.max(0, (80 - score) / 80);
      }, 0) / t.targetDimensions.length;

      return { ...t, roi: roi * (1 + relevanceBoost * 0.5) };
    })
    .sort((a, b) => b.roi - a.roi);
}

export function buildPlan(treatments: Treatment[]): TreatmentPlan {
  const skincare = treatments.filter(t => t.category === 'skincare');
  const professional = treatments.filter(t => t.category === 'professional');

  return {
    economy: [
      ...skincare.slice(0, 3),
    ],
    standard: [
      ...skincare.slice(0, 5),
      ...professional.slice(0, 1),
    ],
    premium: [
      ...skincare.slice(0, 6),
      ...professional.slice(0, 3),
    ],
  };
}
